# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@1
  displayName: Terraform Install
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@0
  displayName: Terraform Init
  inputs:
    command: 'init'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  displayName: Terraform Plan
  inputs:
    command: 'plan'
    environmentServiceNameAzureRM: 'AzureServiceConnection'
    allowTelemetryCollection: false

- task: TerraformCLI@0
  displayName: Terraform Apply
  inputs:
    command: 'apply'
    environmentServiceNameAzureRM: 'AzureServiceConnection'
    allowTelemetryCollection: true

- task: TerraformTaskV4@4
  displayName: Terraform Destroy
  inputs:
    provider: 'azurerm'
    command: 'destroy'
    environmentServiceNameAzureRM: 'AzureServiceConnection'


